name: Onboarding-workflow

on:  workflow_dispatch 
jobs:
  read-spreadsheet:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: set variables
        run: |
              pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
              python Read.py > user_data.txt 
              VAR=$(cat user_data.txt)
              echo "The variable value is $VAR"
              echo "::set-output name=username::$VAR"
              echo "asdas"  
        id: setvariables      
         outputs: 
          username: ${{ steps.setvariables.outputs.username }}
               #sleep 30
              
      - name: Install Dependencies
        run: echo  ${{ jobs.read-spreadsheet.outputs.username }}
