name: Onboarding-workflow

on:  workflow_dispatch 
jobs:
  read-spreadsheet:
    runs-on: ubuntu-latest  
    outputs:
     my_variable: $VAR
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install Dependencies,run scripts and set variables
        run: |
              pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
              python Read.py > user_data.txt 
              VAR=$(cat user_data.txt)
              echo "The variable value is $VAR"
              echo "::set-output name=my_variable::$VAR"
              #echo "::set-output name={name}::{value}"
      - name: Save state
        uses: actions/save-state@v2
        id: save_state
        with:
         state: ${{ steps.set_state.outputs.my_variable }}
              
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: user-artifact
          path: user_data.txt
          if-no-files-found: error
          retention-days: 90
      
 
  prepare-issues:
    runs-on: ubuntu-latest  
    needs:  read-spreadsheet
    steps:
    - name: Download artifact and read
      uses: actions/download-artifact@v3
      with:
         name: user-artifact
         path: user_data.txt
         run: ls -R
    
  
          
          
           
             
