name: Onboarding-workflow

on: workflow_dispatch
jobs:
  read-spreadsheet:
    runs-on: ubuntu-latest
    outputs:
      uname: ${{ steps.setvariables.outputs.username }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: set variables
        id: setvariables
        run: |
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
          python verify_read.py > user_data.txt  
          #cat user_data.txt
          my_string=$(cat user_data.txt)
          IFS=','
          read -ra my_array <<< "$my_string"
          echo "::set-output name=username::${my_array[0]}"
           #sleep 30
  create-repo:
    runs-on: ubuntu-latest
    needs: read-spreadsheet
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Read values from another Job
        run: echo ${{needs.read-spreadsheet.outputs.uname}}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Create New Repository
        run: |
          repo_name="ps-accreditation-${{needs.read-spreadsheet.outputs.uname}}"
          description="This is my new repository."
           curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
             -d "{\"name\":\"$repo_name\",\"description\":\"$description\"}" \
             "https://api.github.com/orgs/im-accreditation/repos"

      - name: Clone New Repository
        run: |
          git clone "https://github.com/im-accreditation/ps-accreditation-${{needs.read-spreadsheet.outputs.uname}}.git"
          cd "ps-accreditation-${{needs.read-spreadsheet.outputs.uname}}"
      - name: Loop through files in folder
        run: |
          for file in ./docs/*.docx
          do
            title=$(basename "$file")
            body=$(pandoc "$file")
            json=$(echo '{}' | jq --arg title "$title" --arg body "$body" '.title=$title | .body=$body')
            curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "$json" \
                 "https://api.github.com/repos/im-accreditation/ps-accreditation-${{needs.read-spreadsheet.outputs.uname}}/issues"
          done
        shell: bash
  append-text:
    runs-on: ubuntu-latest
    needs: read-spreadsheet
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Append Text
        run: echo "New Text" >> completed.txt
      - name: Commit Changes
        run: |
          git status
          git config --global user.email "surya.raghava@infomagnus.com"
          git config --global user.name "suryaraghava80"
          git commit -a -m "Append new text to file"
      - name: Push Changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUBB_TOKEN }}
