name: Onboarding-workflow

on:  workflow_dispatch 
jobs:
  read-spreadsheet:
    runs-on: ubuntu-latest  
    outputs:
      output1: ${{ steps.setvariables.outputs.username }}
    steps:
       
      - name: Checkout Code
        uses: actions/checkout@v2     
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: set variables
        id: setvariables   
        run: |
              pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
              python Read.py > user_data.txt 
              VAR=$(cat user_data.txt)
              echo "The variable value is $VAR"
               echo "::set-output name=username::$VAR"
               #sleep 30
  create-repo:
    runs-on: ubuntu-latest  
    needs: read-spreadsheet
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
      - name: Test
        run: echo "$OUTPUT1"
        
 
            
       
    
          
             
