name: Onboarding-workflow

on:  workflow_dispatch 
jobs:
  read-spreadsheet:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: setvariables
        run: |
              pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
              python Read.py > user_data.txt 
              VAR=$(cat user_data.txt)
              echo "The variable value is $VAR"
              echo "::set-output name=username::$VAR"
              echo "asdas"  
        id: setvariables      
         outputs: 
          username: ${{ steps.setvariables.outputs.username }}
               #sleep 30
              
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Create New Repository
        run: |
          repo_name="ps-accreditation-$VAR"
          description="This is my new repository."
          curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
               -d "{\"name\":\"$repo_name\",\"description\":\"$description\"}" \
               "https://api.github.com/orgs/im-accreditation/repos"
        env:
          INPUT_NAME: ${{ steps.input_step.outputs.name }}               

      - name: Clone New Repository
        run: |
          git clone "https://github.com/im-accreditation/ps-accreditation-$VAR.git"
          cd "ps-accreditation-$VAR"
      - name: Loop through files in folder
        run: |
          for file in ./docs/*.docx
          do
            title=$(basename "$file")
            body=$(pandoc "$file")
            json=$(echo '{}' | jq --arg title "$title" --arg body "$body" '.title=$title | .body=$body')
            curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "$json" \
                 "https://api.github.com/repos/im-accreditation/ps-accreditation-${{ github.event.inputs.username }}/issues"
          done
        shell: bash

            
       
    
          
             
