name: Onboarding workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message to print'
        required: true    
jobs:
  dynamic_repo:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     

      - name: Install Dependencies
        run: |
              pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
              python Read.py

