name: Create New Repo with Issues

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message to print'
        required: true    
jobs:
  create_repo:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Create repository for new user
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUBB_TOKEN }}
          script: |
           const repoName = 'my-new-repo-${{ github.event.inputs.message }}'
           const response = await github.repos.createForAuthenticatedUser({ name: repoName })
           console.log(response.data.html_url)
           core.setOutput('repo_url', response.data.html_url)
        env:
          INPUT_NAME: ${{ steps.input_step.outputs.name }}            
          

      - name: Clone New Repository
        run: |
          git clone "https://github.com/im-sandbox-suryaraghava80/my-new-repo-${{ github.event.inputs.message }}.git"
          cd "my-new-repo-${{ github.event.inputs.message }}"

      - name: Loop through files in folder
        run: |
          for file in ./docs/*.docx
          do
            title=$(basename "$file")
            body=$(pandoc "$file")
            json=$(echo '{}' | jq --arg title "$title" --arg body "$body" '.title=$title | .body=$body')
            curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "$json" \
                 "https://api.github.com/repos/im-sandbox-suryaraghava80/my-new-repo-${{ github.event.inputs.message }}/issues"
          done
        shell: bash
