name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: User Data
          path: userdata.txt

      - name: Read userdata file
        run: cat userdata.txt
