name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact and read
        uses: actions/download-artifact@v2
        with:
         name: user-artifact
         
      - name: Set variable
        run: |
          VAR=$(cat user_data.txt)
          echo "The variable value is $VAR"
