name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: User Data output
          path: userdata.txt
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          
      - name: Read userdata file
        run: cat  userdata.txt
