name: Test read artifact file

on: 
  workflow_dispatch  
      

jobs:
  my-other-job:
    runs-on: ubuntu-latest
    needs:  read-spreadsheet
    
    steps:
    - name: Download artifact and read
      uses: actions/download-artifact@v3
      with:
         name: user-artifact
         path: user_data.txt
         run: ls -R
         
    
