name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          workflow: 'Onboarding.yml'
          name: User Data output
          path: /home/runner/work/onboarding-infomagnus/onboarding-infomagnus/userdata.txt
         
          
      - name: Read userdata file
        run: cat  /home/runner/work/onboarding-infomagnus/onboarding-infomagnus/userdata.txt
