name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact and read
        uses: actions/download-artifact@v2
        with:
          workflow: 'Onboarding.yml'
         # inputs: '{"name": "userdata.txt", "path": " /home/runner/work/onboarding-infomagnus/onboarding-infomagnus"}'
          run: | 
            cd /home/runner/work/onboarding-infomagnus/onboarding-infomagnus/
            ls -la 
            cat userdata.txt 
          
         
          
      #- name: Read userdata file
      #  run: cat  /home/runner/work/onboarding-infomagnus/onboarding-infomagnus/userdata.txt
