name: Test read artifact file

on: 
 workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.read-spreadsheet.outputs.output1 }}
      

jobs:
  my-other-job:
    runs-on: ubuntu-latest
    #needs:  Onboarding-workflow
    
    steps:
      - name: Download artifact and read
        uses: actions/download-artifact@v3
        with:
         name: user-artifact
         
    
