name: Test read artifact file

on: [push]

jobs:
  my-other-job:
    runs-on: ubuntu-latest
    needs: Onboarding-workflow
    steps:
      - name: Download artifact and read
        uses: actions/download-artifact@v2
        with:
         name: user-artifact
         
      - name: Set variable
        run: |
              VAR=${{ needs.Onboarding-workflow.outputs.my_variable }}
              echo "The variable value is $VAR"
